OrdererOrgs:
  - Name: Orderer
    Domain: coffeeshop.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: Ming
    Domain: ming.coffeeshop.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2