Organizations:
    - &R4
        Name: R4
        ID: R4
        MSPDir: ./organizations/ordererOrganizations/demo.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('R4.member')"
            Writers:
                Type: Signature
                Rule: "OR('R4.member')"
            Admins:
                Type: Signature
                Rule: "OR('R4.admin')"
    - &R1
        Name: R1
        ID: R1
        MSPDir: ./organizations/peerOrganizations/r1.demo.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('R1.admin', 'R1.peer', 'R1.client')"
            Writers:
                Type: Signature
                Rule: "OR('R1.admin', 'R1.client')"
            Admins:
                Type: Signature
                Rule: "OR('R1.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('R1.peer')"
    - &R2
        Name: R2
        ID: R2
        MSPDir: ./organizations/peerOrganizations/r2.demo.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('R2.admin', 'R2.peer', 'R2.client')"
            Writers:
                Type: Signature
                Rule: "OR('R2.admin', 'R2.client')"
            Admins:
                Type: Signature
                Rule: "OR('R2.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('R2.peer')"

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: o4.demo.com
          Port: 7050
          ClientTLSCert: ./organizations/ordererOrganizations/demo.com/orderers/o4.demo.com/tls/server.crt
          ServerTLSCert: ./organizations/ordererOrganizations/demo.com/orderers/o4.demo.com/tls/server.crt
    Addresses:
        - o4.demo.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    NC4:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *R4
                - *R1
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            X1:
                Organizations:
                    - *R1
                    - *R2